version: 1.0.5.{build}
configuration: Release

image: Visual Studio 2022

skip_tags: true

nuget:
  disable_publish_on_pr: true

clone_depth: 1

test: off

build_script:
- ps: .\build.ps1 Build All

artifacts:
- path: build\packages\**\*.nupkg
  name: NuGet
